# ===========================
# ✅ WakeUpNews Configuration
# ===========================

title: "WakeUpNews"
description: "सच्चाई को सामने लाने वाली आवाज़ – WakeUpNews"
baseurl: "/wakeupnews-site"
url: "https://padowadi.github.io"

# ✅ SEO Friendly Permalink
permalink: /:year/:month/:day/:title.html

# ✅ Markdown Parser
markdown: kramdown

# ✅ Theme
theme: jekyll-theme-minima

# ✅ Plugins for SEO & Feed
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ✅ Extended Discussion (optional)
extended_discussion: false
