# ===========================
# ✅ WakeUpNews Configuration
# ===========================

title: "WakeUpNews"
description: "सच्चाई को सामने लाने वाली आवाज़ – WakeUpNews"
baseurl: "/wakeupnews-site"
url: "https://padowadi.github.io"

# ✅ SEO Friendly Permalink
permalink: /:year/:month/:day/:title.html

# ✅ Markdown Parser
markdown: kramdown

# ✅ Theme
theme: minima

# ✅ Plugins for SEO & Feed
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ✅ Include Folder
include:
  - assets/images

# ✅ Default Settings for All Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "WakeUpNews"
      website_thumbnail: "/assets/images/default-thumbnail.jpg"
