title: "WakeUpNews"
description: "सच्चाई को सामने लाने वाली आवाज़ – WakeUpNews"
baseurl: "/wakeupnews-site"
url: "https://padowadi.github.io"

# Safe permalink for free GitHub Pages
permalink: /:title/

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
