title: "WakeUpNews"
description: "सच्चाई को सामने लाने वाली आवाज़ – WakeUpNews"
baseurl: ""
url: "https://padowadi.github.io/wakeupnews-site"

permalink: /:year/:month/:day/:title/

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
